[package]
name = "breadlang"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
enum_primitive = "0.1.1"
serialport = "4.3.0"